# Examples from Francois Chollet's "Deep learning in Python" 2nd edition


In [12]:
# All-ones or all-zeros tensors
import tensorflow as tf
import numpy as np
x = tf.ones(shape=(2, ))
print(x)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [13]:
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [14]:
y = [1.0, 1.0]
print(type(y))
print(y)

<class 'list'>
[1.0, 1.0]


In [15]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [19]:
# Random Tensors
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.08144975]
 [0.17406964]
 [0.88036585]], shape=(3, 1), dtype=float32)


In [17]:
# np arrays are assignable!
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [18]:
# Expect Error for running this as Tensor constants are not assignable
x = tf.ones(shape=(2, 2))
x[0, 0] = 0.0
print(x)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [21]:
# Variable
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.15759324],
       [ 0.7023137 ],
       [-0.4874358 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [24]:
# Assigning value to a portion of variable
v[0, 0].assign(3.)
print(v)

v.assign_add(tf.ones((3, 1)))

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [2.],
       [2.]], dtype=float32)>


<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [3.],
       [3.]], dtype=float32)>

In [25]:
# Numpy Arrays behave as variables, not constants
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [26]:
a = tf.ones((2, 2))
print("a:\n", a)
b = tf.square(a)
print("b:\n", b)
c = tf.sqrt(a)
print("c:\n", c)
d = b + c
print("d:\n", d)
e = tf.matmul(a, b)
print("e:\n", e)
e *= d
print("e:\n", e)

a:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
b:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
c:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
d:
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
e:
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
e:
 tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [28]:
# Gradient Tape!
in_var = tf.Variable(initial_value=3.)
print("in_var = ", in_var.numpy())  # .numpy() prints only the value

with tf.GradientTape() as tape:
   result = tf.square(in_var)
gradient = tape.gradient(result, in_var)

print("d(in_var**2)/d(in_var) = ", gradient.numpy())

in_var =  3.0
d(in_var**2)/d(in_var) =  6.0


In [30]:
# Using the GradientTape with constant tensor inputs
in_const = tf.constant(4.)
print("in_const = ", in_const.numpy())  # .numpy() prints only the value

with tf.GradientTape() as tape:
   tape.watch(in_const)    # constants are normally not tracked. This one is watched, however.
   result = tf.square(in_const)

gradient = tape.gradient(result, in_const)

print("d(in_const**2)/d(in_const) = ", gradient.numpy())

in_const =  4.0
d(in_const**2)/d(in_const) =  8.0


In [31]:
# Using nested gradient tapes to compute second-order gradients

time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position =  4.905 * time ** 2  # 0.5gt^2 (g = 9.81 m/sec^2)
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

acceleration.numpy()

np.float32(9.81)